### ISSUE TITLE
[WoL] Nightmares: jinx global events are missing so the weapon special wont work.

### ISSUE THREAD

**Issue by knyghtmare** [babaissarkar/frost-mage#1]
Applies to Black Cat and Jinx Beast

**Comment by babaissarkar** [comment]
These events need to be loaded in each scenario, right? https://github.com/knyghtmare/War_of_Legends/blob/master/macros/curse-global-events.cfg

Is this enough: https://github.com/babaissarkar/frost-mage/blob/564c6f81d874685468f58359ffdc50ec4526c80b/_main.cfg#L16 or something else needs to be included?
